# https://github.com/grafana/helm-charts/tree/main/charts/tempo-distributed

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
spec:
  releaseName: tempo
  chart:
    spec:
      chart: tempo-distributed
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: "1.33.0"
  interval: 10m0s
  valuesFrom:
    - kind: ConfigMap
      name: tempo-values
