apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-helm-release
  namespace: redis # Replace with your desired namespace
spec:
  releaseName: my-release
  chart:
    spec:
      chart: redis # Replace with your Helm chart name
      version: 17.3.11 # Replace with your desired chart version
      sourceRef:
        kind: HelmRepository
        name: my-helm-repo
        namespace: flux-system
  interval: 1m
  values:
    persistence:
      enabled: true
    replica:
      count: 3
