apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
  - name: cert-manager-crds
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/base/cert-manager
  prune: true
