apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-crds
  namespace: flux-system
spec:
  interval: 3m0s
  dependsOn:
  - name: sources
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infra/dev/cert-manager-crds
  prune: true
