apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
namespace: cert-manager
resources:
  - release.yaml
configMapGenerator:
  - name: cert-manager-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
