# https://github.com/jetstack/cert-manager/releases

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  releaseName: cert-manager
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: flux-system
      version: "1.15.5"
  interval: 10m0s
#  timeout: 10m0s
#  install:
#    remediation:
#      retries: 50
#  upgrade:
#    remediation:
#      retries: 50
  valuesFrom:
    - kind: ConfigMap
      name: cert-manager-values
